### ISSUE TITLE
BlockSci's Python package requires "requests" but is missing from deps in setup.py

### ISSUE THREAD

**Issue by boshmaf** [citp/BlockSci#151]
https://github.com/citp/BlockSci/blob/67ee51d6c89e145e879181c7f934fddb4ce3b54b/blockscipy/setup.py#L71

After a fresh installation:

```
Python 3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import blocksci
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/boshmaf/projects/BlockSci/blockscipy/blocksci/__init__.py", line 2, in <module>
    from .currency import *
  File "/Users/boshmaf/projects/BlockSci/blockscipy/blocksci/currency.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by taserghar** [comment]
I also got the same error like below:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/BlockSci/blockscipy/blocksci/__init__.py", line 2, in <module>
    from .currency import *
  File "/BlockSci/blockscipy/blocksci/currency.py", line 2, in <module>
    import requests
ImportError: No module named 'requests'
`

 **If anyone gets any solution please post here.**

**Comment by maltemoeser** [comment]
`pip3 install requests` should solve it. We'll add the dependency in the next release
