### ISSUE TITLE
pip install fail on macos

### ISSUE THREAD

**Issue by alexarsh** [citp/BlockSci#298]
I followed the install documentation for macos. Compilation succeeded, but the pip command fail with the following exception: 

```
$ pip install -e blockscipy
Obtaining file:///private/tmp/BlockSci/blockscipy
Requirement already satisfied: multiprocess>=0.70.5 in /Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages (from blocksci==0.5.0) (0.70.8)
Requirement already satisfied: psutil>=5.4.2 in /Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages (from blocksci==0.5.0) (5.6.3)
Requirement already satisfied: pycrypto>=2.6.1 in /Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages (from blocksci==0.5.0) (2.6.1)
Requirement already satisfied: pandas>=0.22.0 in /Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages (from blocksci==0.5.0) (0.25.0)
Requirement already satisfied: dateparser>=0.6.0 in /Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages (from blocksci==0.5.0) (0.7.1)
Requirement already satisfied: dill>=0.3.0 in /Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages (from multiprocess>=0.70.5->blocksci==0.5.0) (0.3.0)
Requirement already satisfied: numpy>=1.13.3 in /Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages (from pandas>=0.22.0->blocksci==0.5.0) (1.16.4)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages (from pandas>=0.22.0->blocksci==0.5.0) (2.8.0)
Requirement already satisfied: pytz>=2017.2 in /Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages (from pandas>=0.22.0->blocksci==0.5.0) (2019.1)
Requirement already satisfied: tzlocal in /Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages (from dateparser>=0.6.0->blocksci==0.5.0) (1.5.1)
Requirement already satisfied: regex in /Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages (from dateparser>=0.6.0->blocksci==0.5.0) (2019.6.8)
Requirement already satisfied: six>=1.5 in /Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages (from python-dateutil>=2.6.1->pandas>=0.22.0->blocksci==0.5.0) (1.12.0)
Installing collected packages: blocksci
  Running setup.py develop for blocksci
    ERROR: Complete output from command /Users/alex/.virtualenvs/XXX/bin/python3.6 -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/BlockSci/blockscipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps:
    ERROR: running develop
    running egg_info
    writing blocksci.egg-info/PKG-INFO
    writing dependency_links to blocksci.egg-info/dependency_links.txt
    writing requirements to blocksci.egg-info/requires.txt
    writing top-level names to blocksci.egg-info/top_level.txt
    reading manifest file 'blocksci.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'blocksci.egg-info/SOURCES.txt'
    running build_ext
    -- pybind11 v2.2.2
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/BlockSci/blockscipy/build/temp.macosx-10.9-x86_64-3.6
    [  3%] Building CXX object CMakeFiles/_blocksci.dir/src/cluster/cluster/cluster_range.cpp.o
    [  3%] Building CXX object CMakeFiles/_blocksci.dir/src/cluster/cluster/cluster_range_methods.cpp.o
    In file included from /tmp/BlockSci/blockscipy/src/cluster/cluster/cluster_range.cpp:8:
    In file included from /tmp/BlockSci/blockscipy/src/cluster/cluster/cluster_range_py.hpp:14:
    In file included from /usr/local/include/blocksci/cluster/cluster.hpp:16:
    In file included from /usr/local/include/blocksci/address/address.hpp:20:
    /usr/local/include/range/v3/view/any_view.hpp:502:53: error: no matching function for call to object of type 'const _size_::fn'
                        return static_cast<std::size_t>(ranges::size(range_box_t::get()));
                                                        ^~~~~~~~~~~~
    /usr/local/include/range/v3/view/any_view.hpp:478:17: note: in instantiation of member function 'ranges::v3::detail::any_view_impl<ranges::v3::stride_view<ranges::v3::slice_view<ranges::v3::any_view<blocksci::Cluster, 31, void> > >, blocksci::Cluster, 31>::size' requested here
                    any_view_impl(Rng rng)
                    ^
    ...
...
    /tmp/BlockSci/blockscipy/src/range_conversion.hpp:317:16: note: in instantiation of function template specialization 'ranges::v3::any_view<ranges::v3::optional<unsigned int>, 31, void>::any_view<ranges::v3::transform_view<ranges::v3::any_view<ranges::v3::optional<blocksci::Cluster>, 31, void>, (lambda at /tmp/BlockSci/blockscipy/src/range_apply_py.hpp:69:69)>, false, nullptr>' requested here
            return ranges::any_view<value_type, range_cat>{std::forward<T>(t)};
                   ^
    /tmp/BlockSci/blockscipy/src/range_apply_py.hpp:69:20: note: (skipping 6 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
                return convertRangeToPython(t | ranges::view::transform([&](auto && item) -> optional_ret {
                       ^
    /tmp/BlockSci/blockscipy/src/range_apply_py.hpp:145:12: note: in instantiation of function template specialization 'pybind11::class_<ranges::v3::any_view<ranges::v3::optional<blocksci::Cluster>, 31, void>>::def<ApplyMethodToRange<ranges::v3::any_view<ranges::v3::optional<blocksci::Cluster>, 31, void>, function_traits<std::__1::function<unsigned int (const blocksci::Cluster &, blocksci::AddressType::Enum)>, true>, std::__1::function<unsigned int (const blocksci::Cluster &, blocksci::AddressType::Enum)>, std::__1::integer_sequence<unsigned long, 0> >, pybind11::arg, char *>' requested here
            cl.def(strdup(propertyName.c_str()), wrapped_func_type{func}, std::forward<Args>(args)..., strdup(ss.str().c_str()));
               ^
    /tmp/BlockSci/blockscipy/src/cluster/cluster/cluster_py.hpp:39:9: note: in instantiation of function template specialization 'ApplyMethodsToRangeImpl<pybind11::class_<ranges::v3::any_view<ranges::v3::optional<blocksci::Cluster>, 31, void>> >::operator()<std::__1::function<unsigned int (const blocksci::Cluster &, blocksci::AddressType::Enum)>, pybind11::arg>' requested here
            func(method_tag, "count_of_type", toFunc(&Cluster::countOfType), "Return the number of addresses of the given type in the cluster", pybind11::arg("address_type"));
            ^
    /tmp/BlockSci/blockscipy/src/range_apply_py.hpp:151:5: note: in instantiation of function template specialization 'AddClusterMethods::operator()<ApplyMethodsToRangeImpl<pybind11::class_<ranges::v3::any_view<ranges::v3::optional<blocksci::Cluster>, 31, void>> > >' requested here
        applier(ApplyMethodsToRangeImpl{cl});
        ^
    /tmp/BlockSci/blockscipy/src/range_apply_py.hpp:159:5: note: in instantiation of function template specialization 'applyMethodsToRange<pybind11::class_<ranges::v3::any_view<ranges::v3::optional<blocksci::Cluster>, 31, void>>, AddClusterMethods>' requested here
        applyMethodsToRange(cls.optionalRange, applier);
        ^
    /tmp/BlockSci/blockscipy/src/cluster/cluster/cluster_range_methods.cpp:19:5: note: in instantiation of function template specialization 'applyMethodsToRange<blocksci::Cluster, AddClusterMethods>' requested here
        applyMethodsToRange(classes, AddClusterMethods{});
        ^
    /usr/local/include/range/v3/size.hpp:85:32: note: candidate template ignored: substitution failure [with R = const ranges::v3::transform_view<ranges::v3::any_view<ranges::v3::optional<blocksci::Cluster>, 31, void>, (lambda at /tmp/BlockSci/blockscipy/src/range_apply_py.hpp:69:69)> &]: no matching function for call to 'impl_'
                    constexpr auto operator()(R &&r) const
                                   ^
    /usr/local/include/range/v3/size.hpp:92:32: note: candidate template ignored: could not match 'reference_wrapper' against 'transform_view'
                    constexpr auto operator()(std::reference_wrapper<T> ref) const
                                   ^
    /usr/local/include/range/v3/size.hpp:99:32: note: candidate template ignored: could not match 'reference_wrapper' against 'transform_view'
                    constexpr auto operator()(ranges::reference_wrapper<T> ref) const
                                   ^
    /usr/local/include/range/v3/utility/iterator.hpp:424:28: note: candidate function not viable: requires 2 arguments, but 1 was provided
                size_type_t<I> operator()(I const& begin, S end) const
                               ^
    12 errors generated.
    make[2]: *** [CMakeFiles/_blocksci.dir/src/cluster/cluster/cluster_range_methods.cpp.o] Error 1
    make[1]: *** [CMakeFiles/_blocksci.dir/all] Error 2
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/BlockSci/blockscipy/setup.py", line 76, in <module>
        'dateparser>=0.6.0'
      File "/Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/tmp/BlockSci/blockscipy/setup.py", line 32, in run
        self.build_extension(ext)
      File "/private/tmp/BlockSci/blockscipy/setup.py", line 57, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command "/Users/alex/.virtualenvs/XXX/bin/python3.6 -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/BlockSci/blockscipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /private/tmp/BlockSci/blockscipy/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/Users/alex/.virtualenvs/XXX/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/tmp/BlockSci/blockscipy/setup.py", line 32, in run
        self.build_extension(ext)
      File "/private/tmp/BlockSci/blockscipy/setup.py", line 57, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command "/Users/alex/.virtualenvs/XXX/bin/python3.6 -c 'import setuptools, tokenize;__file__='"'"'/private/tmp/BlockSci/blockscipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /private/tmp/BlockSci/blockscipy/
$
```

#### Reproduction Steps

```
brew install cmake jsoncpp libjson-rpc-cpp boost openssl jemalloc zstd \
automake libtool google-sparsehash python3
sudo xcode-select --reset

git clone https://github.com/citp/BlockSci.git
cd BlockSci
mkdir release
cd release
cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ..
make
sudo make install

cd ..
pip3 install -e blockscipy
```

#### System Information

Using AMI: no  
BlockSci version: c05cb2f71da184075cb4c05121cb9ae1df15efca  
Blockchain: Bitcoin  
Total memory: 32 GB
MACOS version: 10.14.15
cmake version: 3.15.0
make version: GNU Make 3.81
python version: 3.6.8
pip version: 19.1.1

**Comment by oprearocks** [comment]
That's great @stsonline ! How much resources did you end up allocating to Docker for the build to pass.
