### ISSUE TITLE
Can't install Blocksci failing on pip3 install

### ISSUE THREAD

**Issue by KBOPYM** [citp/BlockSci#453]
BlockSci version: 7.0

I tried every solution I could find, but nothing worked

Here is full log after command:
`C=clang-7 CXX=clang++-7 sudo -H pip3 install -e blockscipy`

`Obtaining file:///root/BlockSci/blockscipy
Requirement already satisfied: dateparser>=0.6.0 in /usr/local/lib/python3.8/dist-packages (from blocksci==0.7.0) (1.0.0)
Requirement already satisfied: multiprocess>=0.70.5 in /usr/local/lib/python3.8/dist-packages (from blocksci==0.7.0) (0.70.11.1)
Requirement already satisfied: pandas>=0.22.0 in /usr/local/lib/python3.8/dist-packages (from blocksci==0.7.0) (1.1.4)
Requirement already satisfied: psutil>=5.4.2 in /usr/local/lib/python3.8/dist-packages (from blocksci==0.7.0) (5.8.0)
Requirement already satisfied: pycrypto>=2.6.1 in /usr/local/lib/python3.8/dist-packages (from blocksci==0.7.0) (2.6.1)
Requirement already satisfied: requests>=2.19.1 in /usr/local/lib/python3.8/dist-packages (from blocksci==0.7.0) (2.25.0)
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from dateparser>=0.6.0->blocksci==0.7.0) (2.7.3)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.8/dist-packages (from dateparser>=0.6.0->blocksci==0.7.0) (2.1)
Requirement already satisfied: regex!=2019.02.19 in /usr/local/lib/python3.8/dist-packages (from dateparser>=0.6.0->blocksci==0.7.0) (2021.3.17)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from dateparser>=0.6.0->blocksci==0.7.0) (2019.3)
Requirement already satisfied: dill>=0.3.3 in /usr/local/lib/python3.8/dist-packages (from multiprocess>=0.70.5->blocksci==0.7.0) (0.3.3)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.22.0->blocksci==0.7.0) (1.19.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.19.1->blocksci==0.7.0) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.19.1->blocksci==0.7.0) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.19.1->blocksci==0.7.0) (2.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.19.1->blocksci==0.7.0) (3.0.4)
Installing collected packages: blocksci
  Running setup.py develop for blocksci
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/BlockSci/blockscipy/setup.py'"'"'; __file__='"'"'/root/BlockSci/blockscipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /root/BlockSci/blockscipy/
    Complete output (71 lines):
    running develop
    running egg_info
    writing blocksci.egg-info/PKG-INFO
    writing dependency_links to blocksci.egg-info/dependency_links.txt
    writing requirements to blocksci.egg-info/requires.txt
    writing top-level names to blocksci.egg-info/top_level.txt
    reading manifest file 'blocksci.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'blocksci/templateMakefile'
    warning: no files found matching 'blocksci/filterTxesExtension.cpp'
    writing manifest file 'blocksci.egg-info/SOURCES.txt'
    running build_ext
    -- pybind11 v2.5.0
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /root/BlockSci/blockscipy/build/temp.linux-x86_64-3.8
    [  1%] Building CXX object CMakeFiles/_blocksci.dir/src/blocksci_range_type.cpp.o
    [  2%] Building CXX object CMakeFiles/_blocksci.dir/src/python_proxy_scripts.cpp.o
    [  3%] Building CXX object CMakeFiles/_blocksci.dir/src/python_proxies_other.cpp.o
    [  4%] Building CXX object CMakeFiles/_blocksci.dir/src/python_range_conversion.cpp.o
    [  6%] Building CXX object CMakeFiles/_blocksci.dir/src/sequence_py.cpp.o
    [  7%] Building CXX object CMakeFiles/_blocksci.dir/src/simple/address_type_proxy.cpp.o
    [  8%] Building CXX object CMakeFiles/_blocksci.dir/src/simple/bool_proxy.cpp.o
    [  9%] Building CXX object CMakeFiles/_blocksci.dir/src/simple/bytes_proxy.cpp.o
    [ 10%] Building CXX object CMakeFiles/_blocksci.dir/src/simple/int_proxy.cpp.o
    [ 12%] Building CXX object CMakeFiles/_blocksci.dir/src/simple/list_proxy.cpp.o
    [ 13%] Building CXX object CMakeFiles/_blocksci.dir/src/simple/string_proxy.cpp.o
    [ 14%] Building CXX object CMakeFiles/_blocksci.dir/src/simple/time_proxy.cpp.o
    [ 15%] Building CXX object CMakeFiles/_blocksci.dir/src/simple/uint160_proxy.cpp.o
    [ 16%] Building CXX object CMakeFiles/_blocksci.dir/src/simple/uint256_proxy.cpp.o
    [ 18%] Building CXX object CMakeFiles/_blocksci.dir/src/generic_proxy/optional.cpp.o
    [ 19%] Building CXX object CMakeFiles/_blocksci.dir/src/generic_proxy/optional_map.cpp.o
    [ 20%] Building CXX object CMakeFiles/_blocksci.dir/src/generic_proxy/range.cpp.o
    [ 21%] Building CXX object CMakeFiles/_blocksci.dir/src/generic_proxy/range_map_optional_core.cpp.o
    [ 22%] Building CXX object CMakeFiles/_blocksci.dir/src/generic_proxy/range_map_optional_other.cpp.o
    [ 24%] Building CXX object CMakeFiles/_blocksci.dir/src/generic_proxy/range_map_optional_scripts.cpp.o
    c++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
    make[2]: *** [CMakeFiles/_blocksci.dir/build.make:609: CMakeFiles/_blocksci.dir/src/blocksci_range_type.cpp.o] Error 4
    make[2]: *** Waiting for unfinished jobs....
    make[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/_blocksci.dir/all] Error 2
    make: *** [Makefile:84: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/BlockSci/blockscipy/setup.py", line 59, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/root/BlockSci/blockscipy/setup.py", line 32, in run
        self.build_extension(ext)
      File "/root/BlockSci/blockscipy/setup.py", line 57, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/BlockSci/blockscipy/setup.py'"'"'; __file__='"'"'/root/BlockSci/blockscipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.`

**Comment by KBOPYM** [comment]
Ok, turns out it needs more than 2Gb of RAM to compile.
